on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  release:
    name: Pull Request Naming Rules
    runs-on: ubuntu-latest

    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: '[major],[minor],[patch],[skip ci]'
          prefix_case_sensitive: true
          verbal_description: 'Should start with one of the following prefixes: [major], [minor], [patch], [skip ci]'
